name: Python Linting

on:
    push:
        branches:['*']
    pull_request: 
        branches:['*']

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8 blak pylint isort
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Lint with flake8
              run: |
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
        
            - name: Lint with pylint
              run: |
                pylint --disable=C0111,R0903,C0103 $(git ls-files '*.py')
                    
            - name: Check formatting with black
              run: |
                black --check --diff .
                
            - name: Check import order with isort
              run: |
                isort --check-only --profile black --diff .



]