name: Basic Python Linting

on:
  push:
    branches: ['*']
  pull_request: 
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pylint isort
          pip install pandas numpy dask matplotlib pyspark
        
      - name: Basic Shell Check
        run: |
          echo "Testing basic shell functionality"
          echo "Current directory: $(pwd)"
          echo "Files in directory: $(ls -la)"
      
      - name: Run Flake8
        run: |
          # Simple flake8 run without any complicated processing
          flake8 . --count --statistics || echo "Flake8 found issues but continuing"
      
      - name: Run Pylint
        run: |
          # Simple pylint run without any complicated processing
          pylint --rcfile=pylintrc $(git ls-files '*.py') || echo "Pylint found issues but continuing"